function [tDraw] = drawRespArray(arrayPerm,cursorPos,cursorColour,globals)

% Draw the textures and borders to backbuffer
for iPos = 1:numel(arrayPerm)
    Screen('DrawTexture',...
        globals.window,...
        globals.textures(arrayPerm(iPos)),...
        [],...
        globals.xyEdgesResp(:,iPos));
end

% Draw the frames for the images to the screen back buffer
% The cursor is not zero indexed
Screen('FrameRect',...
        globals.window,...
        cursorColour,...
        globals.xyEdgesResp(:,(cursorPos)),...
        globals.penWidthPixels)

% Flip the screen
tDraw = Screen('Flip', globals.window, globals.t);

return