function [symImg] = setSymTextures(window)
symImg = struct;
symImg.modPlus = ...
    Screen('MakeTexture', window, imread(".\Imgs\S0.png"));
symImg.oneBack = ...
    Screen('MakeTexture', window, imread(".\Imgs\S1.png"));
symImg.twoBack = ...
    Screen('MakeTexture', window, imread(".\Imgs\S2.png"));
return