function [globals] = showCross(duration, globals)

% Draw the cross
Screen('DrawLines', ...
    globals.window, ...
    globals.cross.coords, ...
    globals.cross.lineWidthPix, ...
    globals.white, ...
    globals.xyCentreScrn', ...
    2);

% Flip the screen
Screen('Flip', globals.window, globals.t);

% Update globals.t so the cross is shown for the intended duration
waitframes = round(duration / globals.ifi);
globals.t = globals.t + (waitframes * globals.ifi);

return